const foodDB = {
    // === VIANDES ET VOLAILLES ===
    "poulet": {cal:165, prot:31, lip:3.6, gluc:0, label:"Poulet (blanc)"},
    "dinde": {cal:135, prot:30, lip:1, gluc:0, label:"Dinde"},
    "escalope dinde": {cal:135, prot:30, lip:1, gluc:0, label:"Escalope de dinde"},
    "boeuf": {cal:250, prot:26, lip:15, gluc:0, label:"Bœuf (steak)"},
    "steak haché": {cal:240, prot:26, lip:15, gluc:0, label:"Steak haché 5%"},
    "steak haché 15%": {cal:270, prot:24, lip:18, gluc:0, label:"Steak haché 15%"},
    "steak haché 20%": {cal:293, prot:23, lip:21, gluc:0, label:"Steak haché 20%"},
    "steak haché surgelé": {cal:270, prot:24, lip:18, gluc:0, label:"Steak haché surgelé"},
    "steak haché pur boeuf": {cal:240, prot:26, lip:15, gluc:0, label:"Steak haché pur bœuf"},
    "viande hachée": {cal:240, prot:26, lip:15, gluc:0, label:"Viande hachée fraîche"},
    "boeuf bourguignon conserve": {cal:140, prot:14, lip:7, gluc:4, label:"Bœuf bourguignon en conserve"},
    "blanquette de veau conserve": {cal:130, prot:13, lip:6, gluc:4, label:"Blanquette de veau en conserve"},
    "navarin d'agneau conserve": {cal:120, prot:12, lip:6, gluc:3, label:"Navarin d'agneau en conserve"},
    "rumsteck": {cal:260, prot:27, lip:16, gluc:0, label:"Rumsteck"},
    "entrecôte": {cal:280, prot:25, lip:20, gluc:0, label:"Entrecôte"},
    "faux filet": {cal:270, prot:26, lip:18, gluc:0, label:"Faux-filet"},
    "filet boeuf": {cal:271, prot:27, lip:17, gluc:0, label:"Filet de bœuf"},
    "onglet": {cal:180, prot:26, lip:8, gluc:0, label:"Onglet"},
    "bavette": {cal:200, prot:26, lip:10, gluc:0, label:"Bavette"},
    "araignée": {cal:200, prot:26, lip:10, gluc:0, label:"Araignée de bœuf"},
    "paleron": {cal:165, prot:21, lip:8, gluc:0, label:"Paleron"},
    "queue boeuf": {cal:296, prot:28, lip:20, gluc:0, label:"Queue de bœuf"},
    "langue boeuf": {cal:284, prot:16, lip:24, gluc:0, label:"Langue de bœuf"},
    "rognon boeuf": {cal:167, prot:23, lip:7.6, gluc:0, label:"Rognon de bœuf"},
    "tripes": {cal:100, prot:15, lip:4, gluc:0, label:"Tripes"},
    "tripes mode caen": {cal:120, prot:14, lip:6, gluc:1, label:"Tripes à la mode de Caen"},
    "pot au feu": {cal:128, prot:14.5, lip:6.1, gluc:2.6, label:"Pot-au-feu"},
    "pot au feu conserve": {cal:125, prot:14, lip:6, gluc:2, label:"Pot-au-feu en conserve"},
    "veau marengo": {cal:160, prot:22, lip:7, gluc:3, label:"Veau Marengo"},
    "veau marengo conserve": {cal:155, prot:21, lip:7, gluc:3, label:"Veau Marengo en conserve"},
    "gigot agneau": {cal:250, prot:26, lip:16, gluc:0, label:"Gigot d'agneau"},
    "cotelette agneau": {cal:330, prot:24, lip:26, gluc:0, label:"Côtelette d'agneau"},
    "epaule agneau": {cal:289, prot:25, lip:21, gluc:0, label:"Épaule d'agneau"},
    "selle agneau": {cal:234, prot:24, lip:16, gluc:0, label:"Selle d'agneau"},
    "navarin agneau plat": {cal:130, prot:15, lip:6, gluc:5, label:"Navarin d'agneau (plat)"},
    "porc filet mignon": {cal:210, prot:27, lip:11, gluc:0, label:"Filet mignon de porc"},
    "cote porc": {cal:260, prot:25, lip:18, gluc:0, label:"Côte de porc"},
    "rotie porc filet": {cal:160, prot:28, lip:4.5, gluc:0, label:"Rôti de porc (filet mignon)"},
    "porc echine": {cal:270, prot:24, lip:20, gluc:0, label:"Échine de porc"},
    "jarret porc": {cal:220, prot:26, lip:12, gluc:0, label:"Jarret de porc"},
    "poitrine porc": {cal:360, prot:14, lip:33, gluc:0, label:"Poitrine de porc"},
    "travers porc": {cal:320, prot:16, lip:28, gluc:0, label:"Travers de porc"},
    "saute porc": {cal:240, prot:26, lip:14, gluc:0, label:"Sauté de porc"},
    "lapin conserve": {cal:170, prot:25, lip:8, gluc:0, label:"Lapin en conserve"},
    "lapin sauce moutarde": {cal:180, prot:24, lip:9, gluc:1, label:"Lapin sauce moutarde"},
    "magret canard": {cal:320, prot:20, lip:27, gluc:0, label:"Magret de canard"},
    "magret fume": {cal:330, prot:19, lip:28, gluc:0, label:"Magret fumé"},
    "confit canard": {cal:350, prot:18, lip:31, gluc:0, label:"Confit de canard"},
    "confit canard conserve": {cal:350, prot:18, lip:31, gluc:0, label:"Confit de canard conserve"},
    "canard entier": {cal:337, prot:19, lip:29, gluc:0, label:"Canard entier"},
    "poulet entier": {cal:165, prot:31, lip:3.6, gluc:0, label:"Poulet entier"},
    "poulet fermier": {cal:170, prot:30, lip:4, gluc:0, label:"Poulet fermier"},
    "poulet roti": {cal:200, prot:28, lip:9, gluc:0, label:"Poulet rôti"},
    "poulet cuit": {cal:190, prot:27, lip:8, gluc:0, label:"Poulet cuit"},
    "cuisses poulet": {cal:210, prot:25, lip:12, gluc:0, label:"Cuisses de poulet"},
    "ailes poulet": {cal:220, prot:24, lip:13, gluc:0, label:"Ailes de poulet"},
    "filet poulet": {cal:165, prot:31, lip:3.6, gluc:0, label:"Filet de poulet"},
    "emince poulet": {cal:165, prot:31, lip:3.6, gluc:0, label:"Émincé de poulet"},
    "dinde entiere": {cal:135, prot:30, lip:1, gluc:0, label:"Dinde entière"},
    "filet dinde": {cal:135, prot:30, lip:1, gluc:0, label:"Filet de dinde"},
    "emince dinde": {cal:135, prot:30, lip:1, gluc:0, label:"Émincé de dinde"},
    "cordon bleu poulet": {cal:250, prot:14, lip:15, gluc:16, label:"Cordon bleu poulet"},
    "cordon bleu dinde": {cal:245, prot:15, lip:14, gluc:16, label:"Cordon bleu dinde"},
    "cordon bleu jambon fromage": {cal:250, prot:14, lip:15, gluc:16, label:"Cordon bleu jambon fromage"},
    "nuggets poulet": {cal:302, prot:14, lip:19, gluc:18, label:"Nuggets de poulet"},
    "nuggets dinde": {cal:295, prot:15, lip:18, gluc:18, label:"Nuggets de dinde"},
    "tenders poulet": {cal:280, prot:16, lip:15, gluc:20, label:"Tenders poulet"},
    "escalope milanaise": {cal:260, prot:20, lip:12, gluc:20, label:"Escalope milanaise"},

    // === CHARCUTERIES ===
    "corned beef": {cal:250, prot:20, lip:18, gluc:0.5, label:"Corned beef"},
    "corned beef conserve": {cal:250, prot:20, lip:18, gluc:0.5, label:"Corned beef en conserve"},
    "jambon blanc": {cal:145, prot:20, lip:7, gluc:0.5, label:"Jambon blanc"},
    "jambon blanc superieur": {cal:145, prot:21, lip:6.5, gluc:0.5, label:"Jambon blanc supérieur"},
    "jambon decouenne degraisse": {cal:145, prot:21, lip:6.5, gluc:0.5, label:"Jambon découenné dégraissé"},
    "jambon fume": {cal:150, prot:20, lip:7.5, gluc:0.5, label:"Jambon fumé"},
    "jambon cru": {cal:210, prot:27, lip:11, gluc:0, label:"Jambon cru"},
    "jambon sec": {cal:210, prot:27, lip:11, gluc:0, label:"Jambon sec"},
    "jambon serrano": {cal:220, prot:28, lip:12, gluc:0, label:"Jambon Serrano"},
    "jambon italien": {cal:230, prot:27, lip:13, gluc:0, label:"Jambon italien"},
    "jambon parme": {cal:230, prot:27, lip:13, gluc:0, label:"Jambon de Parme"},
    "jambon de pays": {cal:210, prot:27, lip:11, gluc:0, label:"Jambon de pays"},
    "jambon cuit superieur": {cal:145, prot:20, lip:7, gluc:0.5, label:"Jambon cuit supérieur"},
    "jambon a la coupe": {cal:145, prot:20, lip:7, gluc:0.5, label:"Jambon à la coupe"},
    "saucisson sec": {cal:380, prot:25, lip:30, gluc:2, label:"Saucisson sec"},
    "saucisson a l ail": {cal:380, prot:25, lip:30, gluc:2, label:"Saucisson à l'ail"},
    "saucisson brioche": {cal:400, prot:18, lip:25, gluc:28, label:"Saucisson brioché"},
    "saucisson lyonnais": {cal:380, prot:25, lip:30, gluc:2, label:"Saucisson lyonnais"},
    "saucisson pistache": {cal:390, prot:24, lip:31, gluc:2, label:"Saucisson pistache"},
    "chorizo": {cal:450, prot:24, lip:38, gluc:3, label:"Chorizo"},
    "chorizo doux": {cal:440, prot:24, lip:37, gluc:3, label:"Chorizo doux"},
    "chorizo fort": {cal:450, prot:24, lip:38, gluc:3, label:"Chorizo fort"},
    "chorizo bellota": {cal:480, prot:25, lip:40, gluc:2, label:"Chorizo bellota"},
    "mortadelle": {cal:320, prot:16, lip:27, gluc:2, label:"Mortadelle"},
    "coppa": {cal:350, prot:25, lip:27, gluc:1, label:"Coppa"},
    "bresaola": {cal:200, prot:33, lip:6, gluc:1, label:"Bresaola"},
    "salami": {cal:420, prot:22, lip:35, gluc:2, label:"Salami"},
    "salami milano": {cal:420, prot:22, lip:35, gluc:2, label:"Salami Milano"},
    "salami hongrois": {cal:430, prot:21, lip:36, gluc:2, label:"Salami Hongrois"},
    "andouille": {cal:300, prot:20, lip:24, gluc:0.5, label:"Andouille"},
    "andouillette": {cal:320, prot:18, lip:27, gluc:1, label:"Andouillette"},
    "boudin blanc": {cal:280, prot:12, lip:24, gluc:4, label:"Boudin blanc"},
    "boudin noir": {cal:350, prot:15, lip:30, gluc:3, label:"Boudin noir"},
    "boudin antillais": {cal:310, prot:13, lip:26, gluc:5, label:"Boudin antillais"},
    "cervelas": {cal:310, prot:14, lip:27, gluc:2, label:"Cervelas"},
    "saucisse strasbourg": {cal:320, prot:15, lip:28, gluc:2, label:"Saucisse de Strasbourg"},
    "saucisse knacky": {cal:320, prot:15, lip:28, gluc:2, label:"Saucisse knacky"},
    "saucisse knacki": {cal:320, prot:15, lip:28, gluc:2, label:"Saucisse Knacki"},
    "saucisse toulouse": {cal:330, prot:16, lip:29, gluc:1, label:"Saucisse de Toulouse"},
    "saucisse francfort": {cal:310, prot:15, lip:27, gluc:2, label:"Saucisse de Francfort"},
    "saucisse fumee": {cal:320, prot:15, lip:28, gluc:2, label:"Saucisse fumée"},
    "saucisse fumee porc": {cal:320, prot:15, lip:28, gluc:2, label:"Saucisse fumée porc"},
    "merguez": {cal:330, prot:16, lip:29, gluc:2, label:"Merguez"},
    "bacon": {cal:540, prot:12, lip:50, gluc:1, label:"Bacon"},
    "lardons": {cal:420, prot:16, lip:40, gluc:1, label:"Lardons"},
    "pate foie": {cal:380, prot:14, lip:35, gluc:2, label:"Pâté de foie"},
    "pate campagne": {cal:360, prot:15, lip:32, gluc:2, label:"Pâté de campagne"},
    "pate croute": {cal:370, prot:14, lip:30, gluc:6, label:"Pâté en croûte"},
    "terrine porc": {cal:350, prot:16, lip:30, gluc:2, label:"Terrine de porc"},
    "terrine canard": {cal:360, prot:17, lip:31, gluc:2, label:"Terrine de canard"},
    "terrine campagne": {cal:350, prot:16, lip:30, gluc:2, label:"Terrine de campagne"},
    "rillettes": {cal:420, prot:16, lip:38, gluc:0.5, label:"Rillettes"},
    "rillettes porc": {cal:420, prot:16, lip:38, gluc:0.5, label:"Rillettes de porc"},
    "rillettes oie": {cal:450, prot:18, lip:42, gluc:0.5, label:"Rillettes d'oie"},
    "rillettes canard": {cal:440, prot:17, lip:41, gluc:0.5, label:"Rillettes de canard"},
    "rillettes saumon": {cal:380, prot:14, lip:35, gluc:1, label:"Rillettes de saumon"},
    "rillettes thon": {cal:350, prot:13, lip:32, gluc:1, label:"Rillettes de thon"},,
    // === POISSONS ET FRUITS DE MER ===
    "cabillaud": {cal:82, prot:18, lip:0.7, gluc:0, label:"Cabillaud"},
    "cabillaud surgelé": {cal:82, prot:18, lip:0.7, gluc:0, label:"Cabillaud surgelé"},
    "dos cabillaud": {cal:82, prot:18, lip:0.7, gluc:0, label:"Dos de cabillaud"},
    "colin": {cal:92, prot:18, lip:1.8, gluc:0, label:"Colin"},
    "merlu": {cal:92, prot:18, lip:1.8, gluc:0, label:"Merlu"},
    "merlan": {cal:90, prot:18, lip:1.5, gluc:0, label:"Merlan"},
    "lieu noir": {cal:90, prot:19, lip:1.2, gluc:0, label:"Lieu noir"},
    "eglefin": {cal:71, prot:17, lip:0.5, gluc:0, label:"Églefin"},
    "haddock": {cal:103, prot:22, lip:1.5, gluc:0, label:"Haddock"},
    "saumon": {cal:208, prot:20, lip:13, gluc:0, label:"Saumon"},
    "saumon frais": {cal:208, prot:20, lip:13, gluc:0, label:"Saumon frais"},
    "saumon fume": {cal:265, prot:22, lip:19, gluc:0, label:"Saumon fumé"},
    "saumon conserve": {cal:170, prot:22, lip:9, gluc:0, label:"Saumon en conserve"},
    "thon naturel": {cal:116, prot:26, lip:1, gluc:0, label:"Thon au naturel"},
    "thon a l huile": {cal:280, prot:24, lip:20, gluc:0, label:"Thon à l'huile"},
    "thon salade": {cal:190, prot:14, lip:13, gluc:5, label:"Salade de thon"},
    "sardines a l huile": {cal:250, prot:24, lip:17, gluc:0, label:"Sardines à l'huile"},
    "sardines tomate": {cal:210, prot:23, lip:11, gluc:2, label:"Sardines à la tomate"},
    "sardines grillees": {cal:230, prot:25, lip:13, gluc:0, label:"Sardines grillées"},
    "maquereaux moutarde": {cal:220, prot:18, lip:16, gluc:1, label:"Maquereaux à la moutarde"},
    "maquereaux vin blanc": {cal:205, prot:19, lip:14, gluc:0, label:"Maquereaux au vin blanc"},
    "harengs marines": {cal:160, prot:17, lip:10, gluc:0, label:"Harengs marinés"},
    "harengs fume": {cal:200, prot:18, lip:14, gluc:0, label:"Harengs fumés"},
    "anchois": {cal:160, prot:20, lip:9, gluc:0, label:"Anchois"},
    "truite fumee": {cal:180, prot:19, lip:11, gluc:0, label:"Truite fumée"},
    "sole": {cal:78, prot:16, lip:1.2, gluc:0, label:"Sole"},
    "limande": {cal:78, prot:16, lip:1.3, gluc:0, label:"Limande"},
    "raie": {cal:89, prot:19, lip:1.5, gluc:0, label:"Raie"},
    "rouget": {cal:148, prot:21, lip:7, gluc:0, label:"Rouget"},
    "dorade": {cal:77, prot:17, lip:1.2, gluc:0, label:"Dorade"},
    "loup mer": {cal:90, prot:18, lip:1.5, gluc:0, label:"Loup de mer"},
    "bar": {cal:90, prot:18, lip:1.5, gluc:0, label:"Bar"},
    "espadon": {cal:116, prot:20, lip:4, gluc:0, label:"Espadon"},
    "crevettes roses": {cal:99, prot:24, lip:0.3, gluc:0, label:"Crevettes roses"},
    "crevettes cuites": {cal:99, prot:24, lip:0.3, gluc:0, label:"Crevettes cuites"},
    "crevettes decortiquees": {cal:99, prot:24, lip:0.3, gluc:0, label:"Crevettes décortiquées"},
    "gambas": {cal:98, prot:23, lip:0.5, gluc:0, label:"Gambas"},
    "langoustine": {cal:90, prot:20, lip:1, gluc:0, label:"Langoustine"},
    "homard": {cal:80, prot:18, lip:1, gluc:0, label:"Homard"},
    "langouste": {cal:110, prot:22, lip:2, gluc:0, label:"Langouste"},
    "crabe": {cal:85, prot:18, lip:1.5, gluc:0, label:"Crabe"},
    "tourteau": {cal:85, prot:18, lip:1.5, gluc:0, label:"Tourteau"},
    "moules": {cal:86, prot:12, lip:2.3, gluc:3, label:"Moules"},
    "moules conserve": {cal:86, prot:12, lip:2.3, gluc:3, label:"Moules en conserve"},
    "moules marinees": {cal:110, prot:11, lip:5, gluc:4, label:"Moules marinées"},
    "huitres": {cal:66, prot:9, lip:2.5, gluc:4, label:"Huîtres"},
    "bulots": {cal:100, prot:18, lip:1.5, gluc:3, label:"Bulots"},
    "bigorneaux": {cal:100, prot:18, lip:1.5, gluc:3, label:"Bigorneaux"},
    "palourdes": {cal:95, prot:16, lip:1.5, gluc:4, label:"Palourdes"},
    "coques": {cal:47, prot:9, lip:0.7, gluc:2, label:"Coques"},
    "petoncles": {cal:50, prot:11, lip:0.5, gluc:1, label:"Pétoncles"},
    "calamars": {cal:92, prot:15, lip:1.4, gluc:3, label:"Calamars"},
    "anneaux calamar": {cal:92, prot:15, lip:1.4, gluc:3, label:"Anneaux de calamar"},
    "seiche": {cal:90, prot:16, lip:1.4, gluc:3, label:"Seiche"},
    "poulpe": {cal:70, prot:13, lip:1.2, gluc:2, label:"Poulpe"},
    "surimi": {cal:100, prot:8, lip:3, gluc:10, label:"Surimi"},
    "batonnets surimi": {cal:100, prot:8, lip:3, gluc:10, label:"Bâtonnets de surimi"},
    "poisson pane surgelé": {cal:230, prot:13, lip:11, gluc:20, label:"Poisson pané surgelé"},
    "batonnets de poisson": {cal:230, prot:12, lip:11, gluc:20, label:"Bâtonnets de poisson"},
    
    // === ŒUFS, LAITIERS, FROMAGES ===
    "oeuf": {cal:155, prot:13, lip:11, gluc:1.1, label:"Œuf entier"},
    "blanc d'oeuf": {cal:52, prot:11, lip:0.2, gluc:0.7, label:"Blanc d'œuf"},
    "jaune d'oeuf": {cal:322, prot:16, lip:27, gluc:1.2, label:"Jaune d'œuf"},
    "oeuf bio": {cal:155, prot:13, lip:11, gluc:1.1, label:"Œufs bio"},
    "oeuf coque": {cal:155, prot:13, lip:11, gluc:1.1, label:"Œuf à la coque"},
    "lait entier uht": {cal:61, prot:3.2, lip:3.3, gluc:4.8, label:"Lait entier UHT"},
    "lait demi ecreme uht": {cal:46, prot:3.2, lip:1.6, gluc:4.8, label:"Lait demi-écrémé UHT"},
    "lait ecreme uht": {cal:34, prot:3.3, lip:0.1, gluc:5, label:"Lait écrémé UHT"},
    "lait frais": {cal:61, prot:3.2, lip:3.3, gluc:4.8, label:"Lait frais"},
    "lait bio": {cal:61, prot:3.2, lip:3.3, gluc:4.8, label:"Lait bio"},
    "lait sans lactose": {cal:46, prot:3.2, lip:1.6, gluc:4.8, label:"Lait sans lactose"},
    "lait concentre sucre": {cal:330, prot:8, lip:8, gluc:55, label:"Lait concentré sucré"},
    "lait concentre non sucre": {cal:140, prot:9, lip:8, gluc:10, label:"Lait concentré non sucré"},
    "lait en poudre": {cal:500, prot:26, lip:27, gluc:38, label:"Lait en poudre"},
    "boisson amande": {cal:25, prot:0.5, lip:1.5, gluc:2, label:"Boisson amande"},
    "boisson soja": {cal:40, prot:3, lip:2, gluc:2, label:"Boisson soja"},
    "boisson avoine": {cal:45, prot:1, lip:1.5, gluc:7, label:"Boisson avoine"},
    "boisson riz": {cal:55, prot:0.3, lip:1, gluc:11, label:"Boisson riz"},
    "boisson coco": {cal:25, prot:0.2, lip:1.5, gluc:2, label:"Boisson coco"},
    "yaourt nature sucre": {cal:90, prot:4, lip:2.5, gluc:13, label:"Yaourt nature sucré"},
    "yaourt nature non sucre": {cal:59, prot:5, lip:2, gluc:5, label:"Yaourt nature non sucré"},
    "yaourt brasse": {cal:80, prot:4.5, lip:3, gluc:8, label:"Yaourt brassé"},
    "yaourt ferme": {cal:80, prot:4.5, lip:3, gluc:8, label:"Yaourt ferme"},
    "yaourt aux fruits": {cal:90, prot:3.8, lip:2.5, gluc:13, label:"Yaourt aux fruits"},
    "yaourt aromatise vanille": {cal:90, prot:3.8, lip:2.5, gluc:13, label:"Yaourt aromatisé vanille"},
    "yaourt grec": {cal:120, prot:5, lip:9, gluc:4, label:"Yaourt grec"},
    "skyr": {cal:65, prot:11, lip:0.2, gluc:4, label:"Skyr"},
    "fromage blanc 0%": {cal:45, prot:8, lip:0.2, gluc:4, label:"Fromage blanc 0%"},
    "fromage blanc entier": {cal:73, prot:8, lip:3, gluc:4, label:"Fromage blanc entier"},
    "fromage blanc sucre": {cal:110, prot:6, lip:3, gluc:15, label:"Fromage blanc sucré"},
    "petit suisse nature": {cal:123, prot:8.8, lip:9, gluc:2.5, label:"Petit-Suisse nature"},
    "petit suisse sucre": {cal:150, prot:7, lip:9, gluc:12, label:"Petit-Suisse sucré"},
    "camembert lait cru": {cal:300, prot:20, lip:24, gluc:0.5, label:"Camembert lait cru"},
    "camembert pasteurise": {cal:300, prot:20, lip:24, gluc:0.5, label:"Camembert pasteurisé"},
    "brie": {cal:334, prot:21, lip:28, gluc:0.5, label:"Brie"},
    "coulommiers": {cal:320, prot:21, lip:26, gluc:0.5, label:"Coulommiers"},
    "emmental rape": {cal:382, prot:29, lip:29, gluc:0.5, label:"Emmental râpé"},
    "emmental bloc": {cal:382, prot:29, lip:29, gluc:0.5, label:"Emmental bloc"},
    "comte": {cal:410, prot:28, lip:32, gluc:0.5, label:"Comté"},
    "beaufort": {cal:420, prot:28, lip:33, gluc:0.5, label:"Beaufort"},
    "gruyere": {cal:413, prot:29, lip:33, gluc:0, label:"Gruyère"},
    "raclette": {cal:350, prot:25, lip:27, gluc:1, label:"Raclette"},
    "reblochon": {cal:320, prot:22, lip:26, gluc:0.5, label:"Reblochon"},
    "mozzarella": {cal:280, prot:28, lip:17, gluc:2.2, label:"Mozzarella"},
    "mozzarella rapee": {cal:300, prot:25, lip:20, gluc:2, label:"Mozzarella râpée"},
    "burrata": {cal:300, prot:16, lip:26, gluc:1, label:"Burrata"},
    "ricotta": {cal:174, prot:11, lip:13, gluc:3, label:"Ricotta"},
    "ricotta salata": {cal:354, prot:20, lip:29, gluc:2, label:"Ricotta salata"},
    "fromage chevre": {cal:260, prot:19, lip:20, gluc:1, label:"Fromage de chèvre"},
    "buche chevre": {cal:260, prot:19, lip:20, gluc:1, label:"Bûche de chèvre"},
    "crottin chevre": {cal:260, prot:19, lip:20, gluc:1, label:"Crottin de chèvre"},
    "chevre frais": {cal:220, prot:16, lip:17, gluc:1.5, label:"Chèvre frais"},
    "roquefort": {cal:369, prot:21, lip:31, gluc:0.5, label:"Roquefort"},
    "bleu auvergne": {cal:350, prot:20, lip:29, gluc:0.5, label:"Bleu d'Auvergne"},
    "fourme ambert": {cal:350, prot:20, lip:29, gluc:0.5, label:"Fourme d'Ambert"},
    "gorgonzola": {cal:350, prot:20, lip:29, gluc:0.5, label:"Gorgonzola"},
    "fromage tartiner nature": {cal:250, prot:6, lip:23, gluc:4, label:"Fromage à tartiner nature"},
    "kiri": {cal:290, prot:8, lip:27, gluc:3, label:"Kiri"},
    "vache qui rit": {cal:280, prot:10, lip:25, gluc:3, label:"Vache qui rit"},
    "beurre doux": {cal:717, prot:0.9, lip:81, gluc:0.1, label:"Beurre doux"},
    "beurre demi sel": {cal:717, prot:0.9, lip:81, gluc:0.1, label:"Beurre demi-sel"},
    "beurre allege": {cal:450, prot:0.8, lip:50, gluc:0.5, label:"Beurre allégé"},
    "beurre baratte": {cal:717, prot:0.9, lip:81, gluc:0.1, label:"Beurre de baratte"},
    "margarine": {cal:720, prot:0.5, lip:80, gluc:0.5, label:"Margarine"},
    "creme fraiche epaisse": {cal:300, prot:2, lip:30, gluc:3, label:"Crème fraîche épaisse"},
    "creme fraiche liquide": {cal:300, prot:2, lip:30, gluc:3, label:"Crème fraîche liquide"},
    "creme allegee": {cal:160, prot:2, lip:15, gluc:4, label:"Crème allégée"},
    "creme entiere": {cal:300, prot:2, lip:30, gluc:3, label:"Crème entière"},